version: '3.1'

services:

  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648

  orchestratorapi:
    container_name: Orchestrator.API
    build:
      context: .
      dockerfile: Orchestrator.API\Dockerfile
    ports:
      - "5103:80"
    depends_on:
      - rabbitmq

  orchestratorbackgroundtasks:
    container_name: Orchestrator.BackgroundTasks
    build:
      context: .
      dockerfile: Orchestrator.BackgroundTasks\Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq
  
  orchestratorsignalrhub:
    container_name: Orchestrator.SignalrHub
    build:
      context: .
      dockerfile: Orchestrator.SignalrHub\Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq
